### ISSUE TITLE
Eats backslashes

### ISSUE THREAD

**Issue by martin-langhoff** [jwerle/mush#6]
Examples using cat to remove the shell parsing implicit in using `echo`.

```
$ cat somefile
foo\wbar
$ cat somefile | ./mush.sh
foowbar
$ cat somefile | ./mush.sh > someoutput
$ cat someoutput
foowbar
```

**Comment by martin-langhoff** [comment]
After some experimentation with replacing `echo ${line}` in some places with `printf %q "${line}` and `read -r` (see http://stackoverflow.com/questions/924388/sh-read-command-eats-slashes-in-input ) I might have a fix.

**Comment by jwerle** [comment]
Ah good catch. I'd happily accept a PR !
